// ----- // ----- /LIBRARY/ ----- // ----- //
import Link from "next/link";
// ----- // ----- /COMPONENTS/ ----- // ----- //
import Navigation from "@/components/Navigation";
// ----- // ----- /DEFAULT/ ----- // ----- //
import "./globals.css";
import { Inter } from "next/font/google";
// ----- // ----- // ----- // ----- //

const inter = Inter({ subsets: ["latin"] });

// ----- // ----- /FUNCTION/ ----- // ----- //
export const metadata = {
  title: "My first next13 app",
  description: "Generated by create next app",
  keywords: "next13,epale",
};

// ----- // ----- /PAGE/ ----- // ----- //
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  );
}

/** Note -->
- Layaout is a tempalte for all page in nextjs13
- we can specific layout for a single page.
*/