//-----//-----//-----//-----//IMPORT//-----//-----//-----//-----//
import Link from "next/link";
//-----//-----//-----//-----//IMPORT//-----//-----//-----//-----//
import Navigation from "@/components/Navigation";
//-----//-----//-----//-----//DEFAULT//-----//-----//-----//-----//
import "./globals.css";
import { Inter } from "next/font/google";
//-----//-----//-----//-----//-----//-----//-----//-----//-----//
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first next13 app",
  description: "Generated by create next app",
  keywords: "next13,epale",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
